lines = [
    '`timescale 1ns/1ps',
    '',
    'module tb_top();',
    '    reg clk;',
    '    reg [1:0] key;',
    '    wire [1:0] ledg;',
    '',
    '    de2_top uut (',
    '        .CLOCK_50(clk),',
    '        .KEY(key),',
    '        .LEDG(ledg)',
    '    );',
    '',
    '    always #10 clk = ~clk;',
    '',
    '    initial begin',
    '        clk = 0;',
    '        key = 2\'b11;',
    '        #200;',
    '        wait(uut.u_snn.done == 1\'b1);',
    '        $display("Inference 1 Done! Winner: %b, Ambient: %d, Drone: %d, t_exit: %d", ',
    '            uut.u_snn.winner, uut.u_snn.spike_cnt_ambient, uut.u_snn.spike_cnt_drone, uut.u_snn.t_exit);',
    '        #1000;',
    '        key = 2\'b10;',
    '        wait(uut.u_snn.done == 1\'b1);',
    '        $display("Inference 2 Done! Winner: %b, Ambient: %d, Drone: %d, t_exit: %d", ',
    '            uut.u_snn.winner, uut.u_snn.spike_cnt_ambient, uut.u_snn.spike_cnt_drone, uut.u_snn.t_exit);',
    '        #1000;',
    '        $finish;',
    '    end',
    '',
    '    integer i;',
    '    integer in_spikes = 0;',
    '    integer hid_spikes = 0;',
    '    always @(posedge clk) begin',
    '        if (uut.u_snn.aer_valid && uut.u_snn.state == 5) begin',
    '            in_spikes = 0;',
    '            for (i=0; i<640; i=i+1) begin',
    '                if (uut.u_snn.aer_bus_out[i]) in_spikes = in_spikes + 1;',
    '            end',
    '            $display("Time %t, TS %d, input spikes: %d", $time, uut.u_snn.t_cnt, in_spikes);',
    '        end',
    '        if (uut.u_snn.u_hidden.out_valid) begin',
    '            hid_spikes = 0;',
    '            for (i=0; i<128; i=i+1) begin',
    '                if (uut.u_snn.u_hidden.out_spike_bus[i]) hid_spikes = hid_spikes + 1;',
    '            end',
    '            $display("Time %t, TS %d, hidden spikes: %d", $time, uut.u_snn.t_cnt, hid_spikes);',
    '        end',
    '    end',
    'endmodule'
]
with open('tb_top.v', 'w') as f:
    for line in lines:
        f.write(line + '\n')
